server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

payos.clientId=${PAYOS_CLIENT_ID:}
payos.apiKey=${PAYOS_API_KEY:}
payos.checksumKey=${PAYOS_CHECKSUM_KEY:}